vich_uploader:
    db_driver: orm
    metadata:
        type: attribute 

    mappings:
        user_images:
            uri_prefix: /images/reclamation
            upload_destination: '%kernel.project_dir%/public/images/reclamation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer