<?php

namespace ContainerVrZINvY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y0Yxj7lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y0Yxj7l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y0Yxj7l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reeclamationRepository' => ['privates', 'App\\Repository\\ReeclamationRepository', 'getReeclamationRepositoryService', true],
        ], [
            'reeclamationRepository' => 'App\\Repository\\ReeclamationRepository',
        ]);
    }
}
