<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRRvAykb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRRvAykb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRRvAykb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRRvAykb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRRvAykb\App_KernelDevDebugContainer([
    'container.build_hash' => 'RRvAykb',
    'container.build_id' => '15c3a576',
    'container.build_time' => 1711845576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRRvAykb');
