<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRUx6aZp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRUx6aZp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRUx6aZp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRUx6aZp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRUx6aZp\App_KernelDevDebugContainer([
    'container.build_hash' => 'RUx6aZp',
    'container.build_id' => '3e203b2e',
    'container.build_time' => 1711657705,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRUx6aZp');
